### ISSUE TITLE
Setup own caching

### ISSUE THREAD

**Issue by Nicolas-Boltz** [PalladioSimulator/Palladio-Build-Nightly#3]
Setup Java Maven caching takes a lot of time for each build project. This often takes >5min in the 'post setup java' job, which saves the new cache.
Additionally, there currently are some errors when downloading the cache at the beginning. This could be because every single job creates a cache file which is > 5Gb large and there might be a race condition in parallel builds.

Some testing should be done to figure out if the situation gets better by implementing a dedicated cache job and not using caching of setup java. Another way to fix this could be to not save the cache after every job, but only create a new cache every once in a while to update some plugins within.

Example for caching maven java:
```
- name: Cache local Maven repository
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-
```
